ZPA_CL
| extend JsonStart = indexof(Message, "{")
| extend CleanMessage = iff(JsonStart >= 0, substring(Message, JsonStart), Message)
| extend ParsedData = parse_json(CleanMessage)
| where isnotnull(ParsedData.AppCount)
| project
    EventVendor="Zscaler",
    EventProduct="Private Access",
    Connector = ParsedData.Connector, 
    CPUUtilization = ParsedData.CPUUtilization, 
    SystemMemoryUtilization = ParsedData.SystemMemoryUtilization, 
    ProcessMemoryUtilization = ParsedData.ProcessMemoryUtilization, 
    AppCount = ParsedData.AppCount, 
    ServiceCount = ParsedData.ServiceCount, 
    TargetCount = ParsedData.TargetCount, 
    AliveTargetCount = ParsedData.AliveTargetCount, 
    ActiveConnectionsToPublicSE = ParsedData.ActiveConnectionsToPublicSE, 
    DisconnectedConnectionsToPublicSE = ParsedData.DisconnectedConnectionsToPublicSE, 
    ActiveConnectionsToPrivateSE = ParsedData.ActiveConnectionsToPrivateSE, 
    DisconnectedConnectionsToPrivateSE = ParsedData.DisconnectedConnectionsToPrivateSE, 
    TransmittedBytesToPublicSE = ParsedData.TransmittedBytesToPublicSE, 
    ReceivedBytesFromPublicSE = ParsedData.ReceivedBytesFromPublicSE, 
    TransmittedBytesToPrivateSE = ParsedData.TransmittedBytesToPrivateSE, 
    ReceivedBytesFromPrivateSE = ParsedData.ReceivedBytesFromPrivateSE, 
    AppConnectionsCreated = ParsedData.AppConnectionsCreated, 
    AppConnectionsCleared = ParsedData.AppConnectionsCleared, 
    AppConnectionsActive = ParsedData.AppConnectionsActive, 
    UsedTCPPortsIPv4 = ParsedData.UsedTCPPortsIPv4, 
    UsedUDPPortsIPv4 = ParsedData.UsedUDPPortsIPv4, 
    UsedTCPPortsIPv6 = ParsedData.UsedTCPPortsIPv6, 
    UsedUDPPortsIPv6 = ParsedData.UsedUDPPortsIPv6, 
    AvailablePorts = ParsedData.AvailablePorts, 
    SystemMaximumFileDescriptors = ParsedData.SystemMaximumFileDescriptors, 
    SystemUsedFileDescriptors = ParsedData.SystemUsedFileDescriptors, 
    ProcessMaximumFileDescriptors = ParsedData.ProcessMaximumFileDescriptors, 
    ProcessUsedFileDescriptors = ParsedData.ProcessUsedFileDescriptors, 
    AvailableDiskBytes = ParsedData.AvailableDiskBytes, 
    MicroTenantID = ParsedData.MicroTenantID,
    Message = CleanMessage;