ZPA_CL
| extend JsonStart = indexof(Message, "{")
| extend CleanMessage = iff(JsonStart >= 0, substring(Message, JsonStart), Message)
| extend ParsedData = parse_json(CleanMessage)
| where isnotnull(ParsedData.AuditOldValue)
| project
    EventVendor="Zscaler",
    EventProduct="Private Access",
    ModifiedTime = ParsedData.ModifiedTime,
    CreationTime = ParsedData.CreationTime,
    ModifiedBy = ParsedData.ModifiedBy,
    RequestID = ParsedData.RequestID,
    SessionID = ParsedData.SessionID,
    AuditOldValue = tostring(ParsedData.AuditOldValue),
    AuditNewValue = tostring(ParsedData.AuditNewValue),
    ObjectType = ParsedData.ObjectType,
    User = ParsedData.User,
    Message = CleanMessage