ZPA_CL
| extend JsonStart = indexof(Message, "{")
| extend CleanMessage = iff(JsonStart >= 0, substring(Message, JsonStart), Message)
| extend ParsedData = parse_json(CleanMessage)
| where isnotnull(ParsedData.PrivateSE)
| project
    EventVendor="Zscaler",
    EventProduct="Private Access",
    LogTimestamp = todatetime(ParsedData.LogTimestamp),
    PrivateSE = tostring(ParsedData.PrivateSE),
    CPUUtilization = todouble(ParsedData.CPUUtilization),
    SystemMemoryUtilization = todouble(ParsedData.SystemMemoryUtilization),
    ProcessMemoryUtilization = todouble(ParsedData.ProcessMemoryUtilization),
    UsedTCPPortsIPv4 = toint(ParsedData.UsedTCPPortsIPv4),
    UsedUDPPortsIPv4 = toint(ParsedData.UsedUDPPortsIPv4),
    UsedTCPPortsIPv6 = toint(ParsedData.UsedTCPPortsIPv6),
    UsedUDPPortsIPv6 = toint(ParsedData.UsedUDPPortsIPv6),
    AvailablePorts = toint(ParsedData.AvailablePorts),
    SystemMaximumFileDescriptors = toint(ParsedData.SystemMaximumFileDescriptors),
    SystemUsedFileDescriptors = toint(ParsedData.SystemUsedFileDescriptors),
    ProcessMaximumFileDescriptors = toint(ParsedData.ProcessMaximumFileDescriptors),
    ProcessUsedFileDescriptors = toint(ParsedData.ProcessUsedFileDescriptors),
    AvailableDiskBytes = tolong(ParsedData.AvailableDiskBytes),
    Message = CleanMessage;